require: rubocop-rails

AllCops:
    NewCops: enable
    Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Rails/HasAndBelongsToMany:
  Enabled: false